# Generated by Django 5.1 on 2024-09-12 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_description'),
        ('organizations', '0001_initial'),
        ('users', '0017_alter_user_open_to_research'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='add_code',
            field=models.CharField(blank=True, max_length=24, unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='courses',
            field=models.ManyToManyField(related_name='organizations', to='courses.course'),
        ),
        migrations.AddField(
            model_name='organization',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='facilitators',
            field=models.ManyToManyField(related_name='organizations', to='users.facilitator'),
        ),
        migrations.AddField(
            model_name='organization',
            name='learners',
            field=models.ManyToManyField(related_name='organizations', to='users.learner'),
        ),
    ]
