# Generated by Django 5.1 on 2024-09-12 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_remove_organization_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationcourse',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 12, 23, 0, 37, 919555, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='organization',
            name='add_code',
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
