# Generated by Django 5.1 on 2024-09-13 02:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organizationcourse_expires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationcourse',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 13, 2, 34, 26, 366866, tzinfo=datetime.timezone.utc)),
        ),
    ]
