# Generated by Django 5.1 on 2024-09-13 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_organizationcourse_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationcourse',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 13, 2, 56, 29, 83941, tzinfo=datetime.timezone.utc)),
        ),
    ]
