# Generated by Django 5.1 on 2024-09-16 02:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_alter_organizationcourse_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationcourse',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 16, 2, 7, 37, 676740, tzinfo=datetime.timezone.utc)),
        ),
    ]
