# Generated by Django 5.1 on 2024-09-16 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_alter_organizationcourse_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_personal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organizationcourse',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 16, 18, 20, 26, 273819, tzinfo=datetime.timezone.utc)),
        ),
    ]
