# Generated by Django 5.1 on 2024-09-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0016_organization_is_personal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationcourse',
            name='expires',
            field=models.DateTimeField(),
        ),
    ]
