# Generated by Django 5.1 on 2024-09-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0017_alter_organizationcourse_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='seats',
            field=models.IntegerField(default=1),
        ),
    ]
