# Generated by Django 5.1 on 2024-09-20 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0018_organization_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationcourse',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_course', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='organizationfacilitator',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_facilitator', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='organizationlearner',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_learner', to='organizations.organization'),
        ),
    ]
