# Generated by Django 5.1 on 2024-09-08 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multiplechoicequestion',
            old_name='prompt',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='selectmanyquestion',
            old_name='prompt',
            new_name='question',
        ),
    ]
