# Generated by Django 5.1 on 2024-09-09 18:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_prompt_multiplechoicequestion_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='course',
            name='fields_of_study',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Accounting', 'Accounting'), ('Accounting (Governmental)', 'Accounting Governmental'), ('Auditing', 'Auditing'), ('Business Law', 'Business Law'), ('Economics', 'Economics'), ('Finance', 'Finance'), ('Information Technology', 'Information Technology'), ('Management Services', 'Management Services'), ('Regulatory Ethics', 'Regulatory Ethics'), ('Specialized Knowledge', 'Specialized Knowledge'), ('Statistics', 'Statistics'), ('Taxes', 'Taxes'), ('Behavioral Ethics', 'Behavioral Ethics'), ('Business Management & Organization', 'Business Management And Organization'), ('Communications and Marketing', 'Communications And Marketing'), ('Computer Software & Applications', 'Computer Software And Applications'), ('Personal Development', 'Personal Development'), ('Personnel / Human Resources', 'Personnel Human Resources'), ('Production', 'Production')], max_length=64), size=None),
        ),
    ]
