# Generated by Django 5.1 on 2024-09-09 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_tags_alter_course_fields_of_study'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldOfStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='selectmanyanswerchoice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='course',
            name='fields_of_study',
        ),
        migrations.RemoveField(
            model_name='course',
            name='tags',
        ),
        migrations.AlterField(
            model_name='course',
            name='knowledge_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='courses.knowledgelevel'),
        ),
        migrations.DeleteModel(
            name='MultipleChoiceAnswerChoice',
        ),
        migrations.DeleteModel(
            name='MultipleChoiceQuestion',
        ),
        migrations.DeleteModel(
            name='SelectManyAnswerChoice',
        ),
        migrations.DeleteModel(
            name='SelectManyQuestion',
        ),
        migrations.AddField(
            model_name='course',
            name='fields_of_study',
            field=models.ManyToManyField(related_name='courses', to='courses.fieldofstudy'),
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='courses', to='courses.tag'),
        ),
    ]
