# Generated by Django 5.1 on 2024-09-09 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_fieldofstudy_knowledgelevel_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='prerequisite_courses',
        ),
        migrations.CreateModel(
            name='CoursePrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_links', to='courses.course')),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_for_links', to='courses.course')),
            ],
            options={
                'unique_together': {('course', 'prerequisite')},
            },
        ),
    ]
