# Generated by Django 5.1 on 2024-09-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_course_prerequisite_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prerequisite_courses',
            field=models.ManyToManyField(related_name='required_for', through='courses.CoursePrerequisite', to='courses.course'),
        ),
    ]
