# Generated by Django 5.1 on 2024-11-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(default='2023-01-01T00:00:00Z'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='reviewed_at',
            field=models.DateTimeField(default='2023-01-01T00:00:00Z'),
            preserve_default=False,
        ),
    ]
