# Generated by Django 5.1 on 2024-11-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_created_at_course_reviewed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='advanced_preparation',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
    ]
