# Generated by Django 5.1 on 2024-11-21 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_advanced_preparation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='advanced_preparation',
            new_name='advance_preparation',
        ),
    ]
