# Generated by Django 5.1 on 2024-09-20 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0019_alter_organizationcourse_organization_and_more'),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='learner',
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='organization_learner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organizations.organizationlearner'),
            preserve_default=False,
        ),
    ]
