# Generated by Django 5.1 on 2024-09-24 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_remove_quizattempt_learner_and_more'),
        ('users', '0023_alter_facilitator_is_personal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='organization_learner',
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='learner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.learner'),
            preserve_default=False,
        ),
    ]
