# Generated by Django 5.1 on 2024-10-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_remove_quizattempt_organization_learner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
