# Generated by Django 5.1 on 2024-11-22 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_rename_advanced_preparation_course_advance_preparation'),
        ('quizzes', '0004_quizattempt_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='learning_objective',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='courses.learningobjective'),
            preserve_default=False,
        ),
    ]
