# Generated by Django 5.1 on 2025-01-10 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_question_learning_objective'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='learning_objective',
        ),
        migrations.AlterUniqueTogether(
            name='questioncompletion',
            unique_together={('quiz_attempt', 'question')},
        ),
    ]
