# Generated by Django 5.1 on 2024-09-26 18:35

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0008_alter_course_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('feedback_prompt', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('feedback', models.TextField(null=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chatbots.prompt')),
            ],
        ),
    ]
