# Generated by Django 5.1 on 2024-09-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='model',
            field=models.TextField(default='chatgpt-4o-latest'),
        ),
    ]
