# Generated by Django 5.1 on 2024-09-26 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0002_conversation_model'),
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='attempt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='modules.learningmoduleattempt'),
            preserve_default=False,
        ),
    ]
