# Generated by Django 5.1 on 2024-10-09 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0003_conversation_attempt'),
        ('courses', '0008_alter_course_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='course',
        ),
        migrations.CreateModel(
            name='PromptIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbots.prompt')),
            ],
        ),
    ]
