# Generated by Django 5.1 on 2024-08-30 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_adminprofile_facilitatorprofile_learnerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilitatorprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='learnerprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='AdminProfile',
        ),
        migrations.DeleteModel(
            name='FacilitatorProfile',
        ),
        migrations.DeleteModel(
            name='LearnerProfile',
        ),
    ]
