# Generated by Django 5.1 on 2024-08-30 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_username_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_email_per_type',
        ),
    ]
