# Generated by Django 5.1 on 2024-08-31 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_user_type_remove_user_username_user_types_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='types',
            new_name='type',
        ),
    ]
