# Generated by Django 5.1 on 2024-09-03 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_types_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='type',
            new_name='profiles',
        ),
    ]
