# Generated by Django 5.1 on 2024-09-06 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_adminprofile_facilitatorprofile_learnerprofile_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminProfile',
            new_name='Admin',
        ),
        migrations.RenameModel(
            old_name='FacilitatorProfile',
            new_name='Facilitator',
        ),
        migrations.RenameModel(
            old_name='LearnerProfile',
            new_name='Learner',
        ),
    ]
