# Generated by Django 5.1 on 2024-09-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_adminprofile_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='name',
            field=models.CharField(default='Test', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facilitator',
            name='name',
            field=models.CharField(default='Test', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learner',
            name='name',
            field=models.CharField(default='Test', max_length=256),
            preserve_default=False,
        ),
    ]
