# Generated by Django 5.1 on 2024-09-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_admin_name_facilitator_name_learner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='description',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='facilitator',
            name='description',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='learner',
            name='description',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
