# Generated by Django 5.1 on 2024-09-12 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_admin_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='organization',
        ),
        migrations.AddField(
            model_name='user',
            name='open_to_research',
            field=models.BooleanField(null=True),
        ),
    ]
