# Generated by Django 5.1 on 2024-09-12 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_user_organization_user_open_to_research'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='open_to_research',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
