# Generated by Django 5.1 on 2024-09-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_description'),
        ('users', '0017_alter_user_open_to_research'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='courses',
            field=models.ManyToManyField(related_name='learners', to='courses.course'),
        ),
    ]
