# Generated by Django 5.1 on 2024-09-12 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_learner_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learner',
            name='courses',
        ),
    ]
