# Generated by Django 5.1 on 2024-09-12 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_learner_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='description',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='name',
        ),
        migrations.RemoveField(
            model_name='facilitator',
            name='description',
        ),
        migrations.RemoveField(
            model_name='facilitator',
            name='name',
        ),
        migrations.RemoveField(
            model_name='learner',
            name='description',
        ),
        migrations.RemoveField(
            model_name='learner',
            name='name',
        ),
    ]
