# Generated by Django 5.1 on 2024-09-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_admin_user_alter_facilitator_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitator',
            name='is_personal',
            field=models.BooleanField(default=False),
        ),
    ]
