# Generated by Django 5.1 on 2024-09-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_facilitator_is_personal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitator',
            name='is_personal',
            field=models.BooleanField(default=True),
        ),
    ]
