# Generated by Django 5.1 on 2024-09-26 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0008_alter_course_title'),
        ('users', '0023_alter_facilitator_is_personal'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='LearningModuleAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('date_submitted', models.DateTimeField(default=None, null=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.learner')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modules.learningmodule')),
            ],
        ),
        migrations.CreateModel(
            name='LearningModulePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField()),
                ('page_number', models.IntegerField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.learningmodule')),
            ],
        ),
        migrations.CreateModel(
            name='LearningModulePageCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spent', models.FloatField(default=0)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.learningmoduleattempt')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modules.learningmodulepage')),
            ],
        ),
    ]
