# Generated by Django 5.1 on 2024-09-27 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_title'),
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningmodule',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
