# Generated by Django 5.1 on 2024-09-27 21:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_alter_learningmodule_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningmodulepage',
            name='content',
        ),
        migrations.AddField(
            model_name='learningmodulepage',
            name='elements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningmodulepage',
            name='title',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
