# Generated by Django 5.1 on 2024-09-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_remove_learningmodulepage_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmodulepage',
            name='page_name',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
