# Generated by Django 5.1 on 2024-10-09 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_title'),
        ('modules', '0004_learningmodulepage_page_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningmoduleattempt',
            name='module',
        ),
        migrations.RemoveField(
            model_name='learningmodulepage',
            name='module',
        ),
        migrations.RemoveField(
            model_name='learningmodulepagecompletion',
            name='page',
        ),
        migrations.RemoveField(
            model_name='learningmodulepagecompletion',
            name='attempt',
        ),
        migrations.AddField(
            model_name='learningmoduleattempt',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='courses.course'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LearningModuleCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(default=0)),
                ('time_spent', models.FloatField(default=0)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.learningmoduleattempt')),
            ],
        ),
        migrations.DeleteModel(
            name='LearningModule',
        ),
        migrations.DeleteModel(
            name='LearningModulePage',
        ),
        migrations.DeleteModel(
            name='LearningModulePageCompletion',
        ),
    ]
