# Generated by Django 5.1 on 2024-10-09 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_title'),
        ('modules', '0005_remove_learningmoduleattempt_module_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningmoduleattempt',
            name='course',
        ),
        migrations.CreateModel(
            name='LearningModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_path', models.TextField()),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
        migrations.AddField(
            model_name='learningmoduleattempt',
            name='module',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='modules.learningmodule'),
            preserve_default=False,
        ),
    ]
