# Generated by Django 5.1 on 2024-10-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserating',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
