# Generated by Django 5.1 on 2024-09-13 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_cartitem_cart_alter_cartitem_product'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('product', 'cart'), name='unique_cart_product'),
        ),
    ]
