# Generated by Django 5.1 on 2024-09-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_currency_remove_order_status_remove_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='session_id',
            field=models.CharField(max_length=128),
        ),
    ]
